tasks:
  - init: npm install && npm run build
    command: npm run dev
ports:
  - port: 3000
    onOpen: open-preview
vscode:
  extensions:
    - sysoev.language-stylus@1.11.0:xX39oruAJ5UQzTNVRdbBaQ==