name: Testing the e2e jest suites

on: 
  push:
   branches:
    - master
    - develop
  pull_request:
   branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name:  bootstrap
      run: npm run bootstrap
    - name: Build
      run: npm run build
    - name: linting
      run: npm run lint
    - name: Jest + puppeteer end to end
      run: npm run jest:e2e
